# Generated by Django 6.0.1 on 2026-02-05 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_character_characteradmin"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CharacterAdmin",
        ),
    ]
