# Generated by Django 6.0.1 on 2026-02-27 15:24

import django.db.models.deletion
import django.utils.timezone
import web.models.blog
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_friend"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=10, unique=True, verbose_name="标签名"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="标题")),
                ("content", models.TextField(verbose_name="正文")),
                (
                    "cover_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=web.models.blog.blog_cover_upload_to,
                        verbose_name="文章封面",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "update_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blogs",
                        to="web.userprofile",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, to="web.tag", verbose_name="标签"
                    ),
                ),
            ],
            options={
                "ordering": ["-create_time"],
            },
        ),
    ]
